serverAddr = "81.71.136.135"
serverPort = 7000
auth.token = "7Vy&DJehe^ZG2TeT"
transport.tcp_mux = true
transport.tcp_keepalive.enabled = true
transport.pool_count = 5
log.level = "info"

[[proxies]]
name = "web"
type = "tcp"
localPort = 7004
remotePort = 9009

[[proxies]]
name = "ssh"
type = "tcp"
localPort = 22
remotePort = 9010